import Stack from "@mui/material/Stack";
import Head from "next/head";
import { useRouter } from "next/router";
import Dashboard from "../../../layouts/dashboard";

export default function Home() {
  const router = useRouter();
  const { appId } = router.query;

  console.log(appId);

  return (
    <>
      <Head>
        <title>Apps</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard>{appId}</Dashboard>
    </>
  );
}
