import Stack from "@mui/material/Stack";
import Head from "next/head";
import { useRouter } from "next/router";
import useApps from "../hooks/useApps";
import Simple from "../layouts/simple";

import Card from "../components/card";

export default function Home() {
  const apps = useApps();
  const router = useRouter();

  if (apps.isLoading) return <div>Loading...</div>;

  if (apps.data) {
    return (
      <>
        <Head>
          <title>Apps</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Simple>
          <Stack direction="row" gap={2}>
            {apps.data.map((item) => (
              <Card
                key={item.id}
                title={item.title}
                label={item.label}
                onClick={() => router.push(`/app/${item.id}`)}
              />
            ))}
          </Stack>
        </Simple>
      </>
    );
  }

  return null;
}
