import Stack from "@mui/material/Stack";
import Head from "next/head";
import { useRouter } from "next/router";
import CircularProgress from "@mui/material/CircularProgress";

import useApps from "../hooks/useApps";
import Simple from "../layouts/simple";
import Card from "../components/card";
import CreateAppModal from "../sections/apps/create-app-modal";

export default function Home() {
  const apps = useApps();
  const router = useRouter();

  if (apps.isLoading)
    return (
      <Stack
        direction="row"
        height="100vh"
        alignItems="center"
        justifyContent="center"
      >
        <CircularProgress size={24} />
      </Stack>
    );

  if (apps.data) {
    return (
      <>
        <Head>
          <title>Apps</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Simple>
          <Stack direction="row" gap={2}>
            {apps.data.map((item) => (
              <Card
                key={item._id}
                title={item.title}
                label={item.label}
                onClick={() => router.push(`/app/${item.id}`)}
              />
            ))}

            {/* <Card label="Create new app" title="Create" onClick={() => {}} /> */}
            <CreateAppModal />
          </Stack>
        </Simple>
      </>
    );
  }

  return null;
}
